import { Component } from 'react'
import "./Footer.css"

// This component template was autogenerated using the rcc abbreviation

export class Footer extends Component {
  render() {
    return (
    <footer>
        <span><strong>About Me Demo - React Example</strong></span>
    </footer>
    )
  }
}

export default Footer
