package com.revature.models;

public class User {

    // Let's start by defining all of the fields for our user

    private int userId;

    private String firstName;

    private String lastName;

    private String username;

    private String password;

    private Role role;

    private static int userIdCounter = 1;

    // Constructors
    // By default there is a no-args constructor in this class let's add a constructor for every parameter
    // except userId and role
    public User(String firstName, String lastName, String username, String password){
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;

        // We don't want to take in userId or role because we want these to be set to a default value
        this.role = Role.CUSTOMER;
        // UserId should be unique across all users and every user needs one
        this.userId = userIdCounter;
        userIdCounter++;
    }

    // Mutators (Getters and Setters)
    public int getUserId(){
        return userId;
    }

    public void setUserId(int userId){
        this.userId = userId;
    }

    // Everything below was automatically generated by IntelliJ
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
}
